### ISSUE TITLE
Fails to start on Windows 10

### ISSUE THREAD

**Issue by msdeibel** [poush/h2#17]
# System
Windows 10 1803
Node 5.4.1

# Repro
git clone https://github.com/poush/h2
cd h2
npm install
npm start

# Error message
```
App threw an error during load

C:\temp\h2\ServiceProviders\providers.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import {youtubeProvider} from './MediaProviders/youtube'
                                                                                                                                                           ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\temp\h2\main.js:3:20)
```

**Comment by msdeibel** [comment]
Same error with NodeJS 10.11.0

**Comment by poush** [comment]
Please try with `npm install --dev`

**Comment by msdeibel** [comment]
Now npm start works telling me to pass "any youtube url". Passing as only command line arg didn't work. Do I need an option flag or a certain URL type from Youtube?

**Comment by poush** [comment]
Thanks for your efforts. If the electron app is running without errors. You just need to copy any youtube url and press `ctrl+shift+v` to run. It should start the video on the H2. 

Just one request, can you please also check if the H2 app apps keep itself above all other apps even when they are running in full-screen mode?

**Comment by poush** [comment]
Thanks
