### ISSUE TITLE
Add translucent mode

### ISSUE THREAD

**Issue by poush** [poush/H2#28]
Let's add the experimental version, then we might be able to create scenarios and conditions when to turn it on automatically.

In experimental version, it will be enabled by a hot key say, alt shift t

**Comment by iblacker** [comment]
I want to work on this one, looked into some ways to implement it. 

Can you explain a bit more on how you want it done? Like the degree of translucency. And any idea on how to get it implemented, because I have been looking into Electron and it doesn't seems to have a way to make window translucent.

**Comment by poush** [comment]
Hi @iblacker, thanks for your interest.

So what I was looking through this feature is to have some level of transparency in the whole app which can be triggered by some key combination as well as from tray menu. In terms of CSS all I was thinking to some "opacity". 

Now, doing this in Electron is pretty simple ( as per my search till now). You can try this: http://electron.rocks/transparent-window/ and instead of setting up background color in RGBA mode, you can set the opacity property since we want the content inside it to be translucent not just the background. You can try different levels of opacity such to get an optimum value. 

Also, there's an additional thing to add through tray menu such that a person can adjust custom opacity. This can be done in separate issue & PR as well so please do create an issue for this once your PR gets merged for the above feature.

**Comment by iblacker** [comment]
Perfect I will take a deeper look into it and work on it over the weekend

**Comment by iblacker** [comment]
I am working on it, I will give an update if that's ok
