### ISSUE TITLE
Add a pull request template.

### ISSUE THREAD

**Issue by poush** [poush/H2#30]
For now the only requirement is to add "Tracking Issue: #XX" in the PRs. This ensures that each PR which is fixing some issue is linked. Also, add a comment stating that "if you are directly creating a PR then please create an issue for it as well"

**Comment by muhtarudinsiregar** [comment]
hi, i think i can help with this, can you provide what information you want for PR template?

**Comment by poush** [comment]
@muhtarudinsiregar thanks for the interest, but it seems like a PR has been already created for this.

**Comment by muhtarudinsiregar** [comment]
owh ok, goodluck with your project :+1:

**Comment by poush** [comment]
Thank you :)
