### ISSUE TITLE
not supporting streaming of 360 videos

### ISSUE THREAD

**Issue by rashmitpankhania** [poush/H2#32]
needs to add support of 360 degree videos of the same api

**Comment by poush** [comment]
Hi @rashmitpankhania, can you confirm that you saying about 360 videos of youtube? If that's the case then it is a good enhancement to add.

**Comment by rashmitpankhania** [comment]
yes @poush  i checked the video of youtube only also you can verify below that screens aare splitting..
![screenshot from 2018-10-07 22-16-56](https://user-images.githubusercontent.com/24410731/46584263-d4d1a800-ca7e-11e8-999d-22cd964ef23c.png)

**Comment by msdeibel** [comment]
Sure, will do.

**Comment by msdeibel** [comment]
Works OK on Win 10. I can also look around the full 360 without any problems.

**Comment by poush** [comment]
@rashmitpankhania It seems working on my Ubuntu 18 as well. Can you please tell me your system specs, maybe someone or I could replicate.

**Comment by rashmitpankhania** [comment]
Chrome version:Version 69.0.3497.100 (Official Build) (64-bit)
Ubuntu 18.04 LTS
CPU AMD-A9 7TH GEN
RAM 4 GB

@poush Please let me know if something else is required

**Comment by poush** [comment]
I also tried on a similar config with chrome version 67, Ubuntu 18.04 and same video. Can you try once again default size? and then on full maximized version? 
Thanks for your efforts!

**Comment by rashmitpankhania** [comment]
tried on the default screen also but still there is splitting of screen

**Comment by poush** [comment]
Closing till someone replicate it or report it again.
