### ISSUE TITLE
Add a shortcut key and tray menu item to reset alwaysOnTop

### ISSUE THREAD

**Issue by poush** [poush/H2#40]
There are some random cases when alwaysOnTop fails, we have to provide the key combination to reset it so that it can be shown again.

**Comment by matheushf** [comment]
Can you show some highlighted code? Some details about where is this happening on your repo, what file/line etc

**Comment by poush** [comment]
It's just a single line for this https://github.com/poush/H2/blob/master/main.js#L29. You will need to add a global keyboard binding and set this config again inside it. A suggestion for the keyboard binding would be `alt + shift + t`

**Comment by saravanan10393** [comment]
@poush  Can i take this.
