### ISSUE TITLE
Add a GIF in the ReadMe

### ISSUE THREAD

**Issue by poush** [poush/H2#41]
Add a GIF (lightweight) instead of the static image in the readme file, which shows how to use the H2. Make sure to remove the current image from the repository as well and the new GIF should be uploaded on the `img` directory.

**Comment by ming060** [comment]
HelIo! I would like to work on this.

**Comment by poush** [comment]
Sure @ming060, please go ahead.

**Comment by poush** [comment]
Parent Issue was: #36
