### ISSUE TITLE
Instead of throwing error, external links should be opened on same window

### ISSUE THREAD

**Issue by poush** [poush/H2#52]
We are currently throwing error in alert form when an external link is clicked. Instead of this we can make this process smoother by sending that URL to `providers` module which will eventually load the require link on the H2.

**Comment by jfstn** [comment]
I'll take care of this.

**Comment by poush** [comment]
Sure!

**Comment by jfstn** [comment]
Hello again, need some clarification. The error is no longer being thrown but load any external link means being able to navigate between any links inside H2?

**Comment by poush** [comment]
> load any external link means being able to navigate to any link inside H2?

Yes, when you click any link that opens a new window, that must be prevented and that is already done but instead of showing an alert, we should open that on the same window. This can be done by passing the new url to `providers` module call as being done when `ctrl/cmd+shift+v` is called.
