### ISSUE TITLE
Preventing play/pause of video on dragging.

### ISSUE THREAD

**Issue by poush** [poush/H2#57]
After today's changes, I can move the whole H2 by dragging it from anywhere in its body. Now, the new issue is when you stop dragging and put it somewhere on your screen, a playing video gets paused and vice-versa.
There must be some way to prevent that.

**Comment by mskuybeda** [comment]
I did not have any issues with dragging and pausing on windows 10.  Here is an example 
![example](https://user-images.githubusercontent.com/28875884/46923706-cdb01a00-cfe9-11e8-9136-a5224ad3141a.gif)

Maybe a MacOS or Linux issuse.

**Comment by poush** [comment]
Thanks for checking out. Dragging on macOS causes it play/pause trigger as well and need to check for Linux.  I will check Dev tools on my mac to see any possible reason for this in mac.
