### ISSUE TITLE
Add controls instructions into Readme file

### ISSUE THREAD

**Issue by mskuybeda** [poush/H2#59]
ctrl+shift+1 for pause and ctrl+shift+2 for play

**Comment by Benjamin-Davies** [comment]
Possibly place the following at the end of the usage section:
It is consistent with the other shortcut formats

* Controls:
  * Pause `Ctrl/Command + Shift + 1`
  * Play `Ctrl/Command + Shift + 2`

**Comment by poush** [comment]
Yes, I actually mentioned it here https://github.com/poush/H2/pull/26#issuecomment-429407385. I think it will be better to have shortcuts.md or keys.md file for this because we may end up with lots of keys. We can link this file in the readme under usage section.

**Comment by Benjamin-Davies** [comment]
Is this good https://github.com/Benjamin-Davies/H2/blob/fix%2359-controls-docs/docs/shortcuts.md
Are there any other shortcuts that should be added?
